### PR TITLE
Fix a small typo

### PR DESCRIPTION
**Pull request by geanders**
Previously: 

> "... and the results will automatically updated"

changed to (change in bold): 

> "and the results will automatically **be** updated"

### CODE REVIEW

**Review by yihui — APPROVED** [review]
Thank you!

**Comment by geanders** [comment]
Of course! I'm enjoying re-reading the book. Hope you're doing well!

**Comment by yihui** [comment]
I'm still surviving... Can't complain :)

**Comment by geanders** [comment]
Glad to hear it!

I saw another small typo, but I'll just keep my own fork open and add commits for any other typos I see and put in a pull request all at once for those, instead of a separate pull request for each.

**Comment by yihui** [comment]
Sounds perfect!

**Pull request merged**
