### PR TITLE
ADEL ALGHAMDI

### PR DESCRIPTION
**Pull request by pq70pq**
MY PROJECT

### CODE REVIEW

**Comment by cderv** [comment]
Hi @pq70pq , what this PR about ? Are you sure you pushed it in the right place?

**Comment by yihui** [comment]
I think this is just an accidental wrong PR.

**Comment by cderv** [comment]
Though so but I don't have access on this repo to close myself 😄

**Comment by yihui** [comment]
Oh I thought it was the rmarkdown-cookbook repo. Okay, I just added you to this repo.

**Pull request closed without merging**
